from typing import Any, List, Optional, Protocol, Tuple

from app.domain.enums import OutfitCategory, TryOnJobStatus, UploadStatus
from app.schemas.pagination import PaginationParams


class UserRepository(Protocol):
    """Protocol for user and authentication session data access."""
    def get_by_id(self, user_id: int) -> Optional[Any]: ...
    def get_by_public_id(self, public_id: str) -> Optional[Any]: ...
    def get_by_email(self, email: str) -> Optional[Any]: ...
    def create(self, public_id: str, email: str, name: str, password_hash: str) -> Any: ...
    def save_session(self, session_public_id: str, user_id: int, refresh_token_hash: str, expires_at: Any) -> Any: ...
    def get_session(self, session_public_id: str) -> Optional[Any]: ...
    def revoke_session(self, session_public_id: str) -> bool: ...


class UploadRepository(Protocol):
    """Protocol for person image upload data access."""
    def get_by_public_id(self, public_id: str) -> Optional[Any]: ...
    def get_by_public_id_and_user_id(self, public_id: str, user_id: int) -> Optional[Any]: ...
    def list_by_user_id(self, user_id: int, pagination: PaginationParams, status: UploadStatus = UploadStatus.ACTIVE) -> Tuple[List[Any], int]: ...
    def create(self, public_id: str, user_id: int, storage_key: str, original_filename: str, mime_type: str, size_bytes: int, width: Optional[int], height: Optional[int]) -> Any: ...
    def mark_deleted(self, public_id: str, user_id: int) -> bool: ...
    def count_active_jobs_for_upload(self, upload_public_id: str) -> int: ...


class OutfitRepository(Protocol):
    """Protocol for outfit catalogue data access."""
    def get_by_public_id(self, public_id: str) -> Optional[Any]: ...
    def get_by_slug(self, slug: str) -> Optional[Any]: ...
    def list_active(self, category: Optional[OutfitCategory], search: Optional[str], pagination: PaginationParams) -> Tuple[List[Any], int]: ...


class FavoriteRepository(Protocol):
    """Protocol for outfit favorites data access."""
    def add(self, user_id: int, outfit_id: int) -> bool: ...
    def remove(self, user_id: int, outfit_id: int) -> bool: ...
    def is_favorited(self, user_id: int, outfit_id: int) -> bool: ...
    def list_by_user_id(self, user_id: int, pagination: PaginationParams) -> Tuple[List[Any], int]: ...


class TryOnRepository(Protocol):
    """Protocol for virtual try-on job and result data access."""
    def get_by_public_id(self, public_id: str) -> Optional[Any]: ...
    def get_by_public_id_and_user_id(self, public_id: str, user_id: int) -> Optional[Any]: ...
    def list_by_user_id(self, user_id: int, pagination: PaginationParams, status: Optional[TryOnJobStatus] = None) -> Tuple[List[Any], int]: ...
    def create_job(self, public_id: str, user_id: int, upload_id: int, outfit_id: int, celery_task_id: Optional[str] = None) -> Any: ...
    def update_status(self, public_id: str, status: TryOnJobStatus, failure_code: Optional[str] = None, failure_reason: Optional[str] = None) -> Any: ...
    def create_result(self, result_public_id: str, job_id: int, storage_key: str, width: int, height: int, execution_time_seconds: Optional[float] = None) -> Any: ...
    def delete_job(self, public_id: str, user_id: int) -> bool: ...
