export { LandingHeader } from "./components/landing-header"
export { LandingFooter } from "./components/landing-footer"
export { SectionShell } from "./components/section-shell"
export { HeroSection } from "./components/hero-section"
export { ProductThesisSection } from "./components/product-thesis-section"
export { HowItWorksSection } from "./components/how-it-works-section"
export { TryOnFlowSection } from "./components/try-on-flow-section"
export { IdentitySection } from "./components/identity-section"
export { OutfitExperienceSection } from "./components/outfit-experience-section"
export { ProcessingSection } from "./components/processing-section"
export { ResultExperienceSection } from "./components/result-experience-section"
export { PrivacySection } from "./components/privacy-section"
export { AsyncUxSection } from "./components/async-ux-section"
export { ResponsiveSection } from "./components/responsive-section"
export { WhatItIsSection } from "./components/what-it-is-section"
export { TrustSection } from "./components/trust-section"
export { FinalCtaSection } from "./components/final-cta-section"
export { TypingHeadline } from "./components/typing-headline"
export { ShimmerCta } from "./components/shimmer-cta"
export { PageProgressController } from "./components/page-progress-controller"

// Export illustrations
export { HeroTryonSvg } from "./illustrations/hero-tryon-svg"
export { HeroAmbientSvg } from "./illustrations/hero-ambient-svg"
export { ThesisGridSvg } from "./illustrations/thesis-grid-svg"
export { FlowDiagramSvg } from "./illustrations/flow-diagram-svg"
export { IdentityLockSvg } from "./illustrations/identity-lock-svg"
export { GarmentRailSvg } from "./illustrations/garment-rail-svg"
export { AsyncStatesSvg } from "./illustrations/async-states-svg"
export { ResultCompareSvg } from "./illustrations/result-compare-svg"
export { PrivacyFlowSvg } from "./illustrations/privacy-flow-svg"
export { DeviceSystemSvg } from "./illustrations/device-system-svg"
export { FinalClosureSvg } from "./illustrations/final-closure-svg"

// Export background patterns
export * from "./patterns"
