from typing import List, Optional, Protocol, Tuple

from app.domain.enums import OutfitCategory, TryOnJobStatus
from app.domain.ownership import CurrentUser
from app.schemas.auth import LoginRequest, RegisterRequest, TokenResponse
from app.schemas.favorite import FavoriteItemResponse, FavoriteToggleResponse
from app.schemas.outfit import OutfitListItem, OutfitQueryFilter, OutfitResponse
from app.schemas.pagination import PaginatedData, PaginationParams
from app.schemas.tryon import (
    CreateTryOnRequest,
    TryOnJobCreatedResponse,
    TryOnJobListItem,
    TryOnJobResponse,
    TryOnQueryFilter,
)
from app.schemas.upload import PersonUploadListItem, PersonUploadResponse
from app.schemas.user import UserProfileResponse


class AuthService(Protocol):
    """Protocol defining authentication business operations."""
    def register(self, payload: RegisterRequest) -> UserProfileResponse: ...
    def login(self, payload: LoginRequest) -> TokenResponse: ...
    def refresh(self, refresh_token: str) -> TokenResponse: ...
    def logout(self, refresh_token: str) -> bool: ...
    def get_current_profile(self, user: CurrentUser) -> UserProfileResponse: ...


class UploadService(Protocol):
    """Protocol defining person image upload business operations."""
    def create_person_upload(self, user: CurrentUser, filename: str, content: bytes, mime_type: str) -> PersonUploadResponse: ...
    def list_person_uploads(self, user: CurrentUser, pagination: PaginationParams) -> PaginatedData[PersonUploadListItem]: ...
    def get_owned_upload(self, user: CurrentUser, upload_id: str) -> PersonUploadResponse: ...
    def delete_owned_upload(self, user: CurrentUser, upload_id: str) -> bool: ...


class OutfitService(Protocol):
    """Protocol defining outfit catalogue business operations."""
    def list_active_outfits(self, filters: OutfitQueryFilter, pagination: PaginationParams, current_user: Optional[CurrentUser] = None) -> PaginatedData[OutfitListItem]: ...
    def get_active_outfit(self, outfit_id: str, current_user: Optional[CurrentUser] = None) -> OutfitResponse: ...


class FavoriteService(Protocol):
    """Protocol defining favorite outfit business operations."""
    def favorite_outfit(self, user: CurrentUser, outfit_id: str) -> FavoriteToggleResponse: ...
    def unfavorite_outfit(self, user: CurrentUser, outfit_id: str) -> FavoriteToggleResponse: ...
    def list_favorites(self, user: CurrentUser, pagination: PaginationParams) -> PaginatedData[FavoriteItemResponse]: ...


class TryOnService(Protocol):
    """Protocol defining virtual try-on workflow orchestration."""
    def create_job(self, user: CurrentUser, payload: CreateTryOnRequest) -> TryOnJobCreatedResponse: ...
    def get_job(self, user: CurrentUser, job_id: str) -> TryOnJobResponse: ...
    def list_jobs(self, user: CurrentUser, filters: TryOnQueryFilter, pagination: PaginationParams) -> PaginatedData[TryOnJobListItem]: ...
    def delete_job(self, user: CurrentUser, job_id: str) -> bool: ...
