from enum import StrEnum


class UploadStatus(StrEnum):
    ACTIVE = "active"
    DELETED = "deleted"


class TryOnJobStatus(StrEnum):
    QUEUED = "queued"
    PROCESSING = "processing"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class OutfitCategory(StrEnum):
    UPPER_BODY = "upper_body"
    LOWER_BODY = "lower_body"
    DRESS = "dresses"


class FailureCode(StrEnum):
    INPUT_MEDIA_MISSING = "INPUT_MEDIA_MISSING"
    INVALID_PERSON_IMAGE = "INVALID_PERSON_IMAGE"
    INVALID_GARMENT_IMAGE = "INVALID_GARMENT_IMAGE"
    UNSUPPORTED_OUTFIT_CATEGORY = "UNSUPPORTED_OUTFIT_CATEGORY"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
    INFERENCE_FAILED = "INFERENCE_FAILED"
    GPU_OUT_OF_MEMORY = "GPU_OUT_OF_MEMORY"
    OUTPUT_INVALID = "OUTPUT_INVALID"
    STORAGE_WRITE_FAILED = "STORAGE_WRITE_FAILED"
    DATABASE_WRITE_FAILED = "DATABASE_WRITE_FAILED"
    QUEUE_SUBMISSION_FAILED = "QUEUE_SUBMISSION_FAILED"
    WORKER_FAILURE = "WORKER_FAILURE"
    UNKNOWN_PROCESSING_ERROR = "UNKNOWN_PROCESSING_ERROR"
