from enum import StrEnum
from typing import Set


class Environment(StrEnum):
    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"
    TESTING = "testing"


class ModelLoadState(StrEnum):
    NOT_LOADED = "not_loaded"
    LOADING = "loading"
    READY = "ready"
    FAILED = "failed"


class PrecisionMode(StrEnum):
    NO = "no"
    FP16 = "fp16"
    BF16 = "bf16"


class TokenType(StrEnum):
    ACCESS = "access"
    REFRESH = "refresh"


class ErrorCode(StrEnum):
    # Base Errors
    APP_ERROR = "APP_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"
    UNAUTHORIZED = "UNAUTHORIZED"
    # Authentication & Session Errors
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN"
    ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    SESSION_REVOKED = "SESSION_REVOKED"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"

    # Uploads & Storage
    UPLOAD_REQUIRED = "UPLOAD_REQUIRED"
    EMPTY_UPLOAD = "EMPTY_UPLOAD"
    UPLOAD_NOT_FOUND = "UPLOAD_NOT_FOUND"
    UPLOAD_IN_USE = "UPLOAD_IN_USE"
    UPLOAD_STORAGE_FAILED = "UPLOAD_STORAGE_FAILED"
    UPLOAD_PERSISTENCE_FAILED = "UPLOAD_PERSISTENCE_FAILED"
    UPLOAD_UNAVAILABLE = "UPLOAD_UNAVAILABLE"
    UNSUPPORTED_IMAGE_TYPE = "UNSUPPORTED_IMAGE_TYPE"
    INVALID_IMAGE = "INVALID_IMAGE"
    IMAGE_TOO_LARGE = "IMAGE_TOO_LARGE"
    IMAGE_DIMENSIONS_INVALID = "IMAGE_DIMENSIONS_INVALID"
    IMAGE_PIXEL_LIMIT_EXCEEDED = "IMAGE_PIXEL_LIMIT_EXCEEDED"
    ANIMATED_IMAGE_NOT_SUPPORTED = "ANIMATED_IMAGE_NOT_SUPPORTED"
    STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"
    STORAGE_ERROR = "STORAGE_ERROR"

    # Outfits & Favorites
    OUTFIT_NOT_FOUND = "OUTFIT_NOT_FOUND"
    OUTFIT_INACTIVE = "OUTFIT_INACTIVE"
    FAVORITE_NOT_FOUND = "FAVORITE_NOT_FOUND"

    # Try-On State & Processing
    TRYON_JOB_NOT_FOUND = "TRYON_JOB_NOT_FOUND"
    TRYON_INVALID_STATE = "TRYON_INVALID_STATE"
    TRYON_JOB_ACTIVE = "TRYON_JOB_ACTIVE"
    TRYON_JOB_IN_PROGRESS = "TRYON_JOB_IN_PROGRESS"
    TRYON_CREATION_FAILED = "TRYON_CREATION_FAILED"
    TRYON_PROCESSING_FAILED = "TRYON_PROCESSING_FAILED"
    TRYON_QUEUE_UNAVAILABLE = "TRYON_QUEUE_UNAVAILABLE"
    QUEUE_SUBMISSION_FAILED = "QUEUE_SUBMISSION_FAILED"
    RESULT_NOT_FOUND = "RESULT_NOT_FOUND"

    # Infrastructure & AI
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    REDIS_UNAVAILABLE = "REDIS_UNAVAILABLE"
    CATVTON_UNAVAILABLE = "CATVTON_UNAVAILABLE"
    CATVTON_CONFIGURATION_ERROR = "CATVTON_CONFIGURATION_ERROR"
    CATVTON_RUNTIME_ERROR = "CATVTON_RUNTIME_ERROR"
    CATVTON_MODEL_LOAD_ERROR = "CATVTON_MODEL_LOAD_ERROR"
    CATVTON_INFERENCE_ERROR = "CATVTON_INFERENCE_ERROR"
    CATVTON_OOM_ERROR = "CATVTON_OOM_ERROR"
    WORKER_UNAVAILABLE = "WORKER_UNAVAILABLE"

    # Rate Limiting & Resource Capacity (Phase 13)
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    TRYON_CAPACITY_LIMIT = "TRYON_CAPACITY_LIMIT"
    TRYON_CAPACITY_UNAVAILABLE = "TRYON_CAPACITY_UNAVAILABLE"
    UPLOAD_TOO_LARGE = "UPLOAD_TOO_LARGE"
    SERVICE_NOT_READY = "SERVICE_NOT_READY"


# File Upload Defaults
DEFAULT_MAX_UPLOAD_BYTES: int = 10 * 1024 * 1024  # 10 MB
ALLOWED_MIME_TYPES: Set[str] = {
    "image/jpeg",
    "image/png",
    "image/webp",
}
ALLOWED_EXTENSIONS: Set[str] = {"jpg", "jpeg", "png", "webp"}

# Pagination Defaults
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
